# PYTHON
[[language]]
name = "python"
language-servers = [ "basedpyright", { name = "ruff", except-features = ["diagnostics"] } ]
auto-format = true

# MARKDOWN
[[language]]
name = "markdown"
language-servers = [ "mpls" ]
auto-format = true
soft-wrap.enable = true

[language-server.mpls]
command = "mpls"
args = ["--theme", "tokyonight", "--enable-emoji", "--no-auto"]

# JSON
[[language]]
name = "json"
auto-format = false
