theme = "base16_terminal"

[editor]
true-color = true
line-number = "relative"
bufferline = "multiple"
end-of-line-diagnostics = "disable"
gutters = ["diagnostics", "line-numbers", "spacer", "diff"]

[editor.inline-diagnostics]
cursor-line = "disable"
other-lines = "disable"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[keys.insert]
"C-[" = "normal_mode"

# YAZI
[keys.normal]
C-y = [
  ':sh rm -f /tmp/unique-file',
  ':insert-output yazi "%{buffer_name}" --chooser-file=/tmp/unique-file',
  ':sh printf "\x1b[?1049h\x1b[?2004h" > /dev/tty',
  ':open %sh{cat /tmp/unique-file}',
  ':redraw',
]
