theme = "t_modus_vivendi_tinted"

[editor]
true-color = true
line-number = "relative"
bufferline = "multiple"
end-of-line-diagnostics = "disable"
gutters = ["diagnostics", "line-numbers", "spacer", "diff"]

[editor.inline-diagnostics]
cursor-line = "disable"
other-lines = "disable"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[keys.normal]
A-l = ":open ~/.config/helix"

[keys.normal.space.t]
"1" = ":theme t_modus_vivendi_tinted"
"2" = ":theme modus_vivendi_tinted"
"3" = ":theme modus_operandi_tinted"
