[[sources]] 
name = "friendly-snippets"  
git = "https://github.com/rafamadriz/friendly-snippets.git" 

[[sources.paths]] 
scope = ["go"]  
path = "snippets/go.json"  

[[sources.paths]] 
scope = ["python"]  
path = "snippets/python/python.json"  
